language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t jeevan-nh/docker-react

script:
  - docker run -e CI=true jeevan-nh/docker-react npm run test -- --coverage
