version: 2.1

jobs:
  build-test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - build-test-image
      - run:
          name: "build image"
          command: "docker build -f Dockerfile.dev . -t jeevan-nh/docker-react"
      - run:
          name: "run tests"
          command: "docker run -e CI=true jeevan-nh/docker-react npm run test -- --coverage"

workflows:
  build-test:
    jobs:
      - build-test
