version: 2.1

jobs:
  build:
    machine: true
    steps:
      # - setup_remote_docker:
      #     version: 19.03.13
      - checkout
      - run: "docker build -f Dockerfile.dev . -t jeevan-nh/docker-react"
      - run: "docker run -e CI=true jeevan-nh/docker-react npm run test -- --coverage"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
