version: 2.1

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: "docker build -f Dockerfile.dev . -t jeevan-nh/docker-react"
  test:
    docker:
      - image: jeevan-nh/docker-react
    steps:
      - checkout
      - run: "docker run -e CI=true jeevan-nh/docker-react npm run test -- --coverage"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
